### ISSUE TITLE
Import-Module SemVerPS fails due to invalid module file

### ISSUE THREAD

**Issue by v-rosa** [Sarafian/SemVerPS#3] opened 2021-02-01 16:05 UTC
Hey, I was testing SemVerPS module after installation and powershell cannot load it due to a invalid module.

Steps to reproduce:

- Install-Module SemVerPS -Scope All
- Close PS shell
- Open new PS shell
- Execute:
```powershell
Import-Module SemVerPS -Verbose
#VERBOSE: Skipping the Version folder 1.0.0 under Module C:\Program Files\WindowsPowerShell\Modules\semverps as it does not have a valid module manifest file
```

How to fix it:

Edit **ModuleVersion** property under `SemVerPS.psd1` to match with the folder version: `C:\Program Files\WindowsPowerShell\Modules\SemVerPS\1.0.0`

**Comment by Sarafian** [comment] 2021-02-05 13:58
Can you share your environment? 

I can't reproduce in PS 7.0.1 and Windows PowerShell 5.1 by installing from the galler with `Install-Module SemVerPS -Force`



```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Import-Module SemVerPS -Verbose
VERBOSE: Loading module from path 'C:\Program Files\PowerShell\Modules\SemVerPS\1.0\SemVerPS.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module SemVerPS.
VERBOSE: Loading module from path 'C:\Program Files\PowerShell\Modules\SemVerPS\1.0\SemVerPS.psm1'.
VERBOSE: Importing function 'Add-SemVerMember'.
VERBOSE: Importing function 'ConvertTo-SemVer'.
VERBOSE: Importing function 'Limit-SemVer'.
VERBOSE: Importing function 'Test-SemVer'.
```


Same applies for 

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by v-rosa** [comment] 2021-02-08 18:38
Hello Sarafian, indeed it works in the versions you mentioned. I've catch this behavior in the following version:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Sarafian** [comment] 2021-02-10 20:24
I cannot reproduce in my PowerShell 5 setup. My version is just a bit higher and I suppose my windows version is higher than yours as well `Windows 10 Version 20H2 (OS Build 19042.789)`

I checked the file system as well and it is installed properly and as expected in `C:\Program Files\WindowsPowerShell\Modules\SemVerPS\1.0`

I also checked the [manifest file](https://www.powershellgallery.com/packages/SemVerPS/1.0/Content/SemVerPS.psd1) in the gallery which correct has a version of `1.0`. I'm thinking that you are somehow getting another version?

If you can try to dive deeper that would be great otherwise I would close this.

**Comment by Sarafian** [comment] 2021-06-21 20:11
Anyhow.
There is a new version `1.1` that should work. It uses the code from version 2.0.6

The issue you had, I had in the AppVeyor setup as well which used the same image.

**Closed as completed** 2021-06-21 20:11 UTC
